-- Legacy migration retired.
--
-- For a clean rebuild, run the complete supabase_schema.sql script. It
-- removes the existing app data and Auth users, recreates the schema and RPCs,
-- and seeds the initial administrator.
